services:
  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    container_name: plausible_events_db
    restart: always
    networks:
      - app
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1',
        ]
      start_period: 1m

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.4
    container_name: plausible
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_events_db:
        condition: service_healthy
    networks:
      - app
    ports:
      - '127.0.0.1:8080:8000'
    volumes:
      - plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - TMPDIR=/var/lib/plausible/tmp
      - BASE_URL=https://xxxxxx.io
      - SECRET_KEY_BASE=Uxxxxxxg==
      - DATABASE_URL=postgres://postgres:xxxxx@172.18.0.1:5432/plausible_db
      - MAILER_EMAIL=send@xxxx.io
      - MAILER_NAME=xxxx.io
      - SMTP_HOST_ADDR=mail.xxxx.io
      - SMTP_HOST_PORT=465
      - SMTP_USER_NAME=send@xxxxx.io
      - SMTP_USER_PWD=xxxxx
      - SMTP_HOST_SSL_ENABLED=true

volumes:
  event-data:
    driver: local
  event-logs:
    driver: local
  plausible-data:
    driver: local

networks:
  app:
    external: true
